/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.edu.ifsul.cc.lpoo.cv.gui.funcionario;

import br.edu.ifsul.cc.lpoo.cv.Controle;

/**
 *
 * @author bruno
 */
public class JPanelFuncionarioFormulario extends javax.swing.JPanel {

    private JPanelFuncionario pnlFuncionario;
    private Controle controle;
    
    public JPanelFuncionarioFormulario(JPanelFuncionario pnlFuncionario, Controle controle) {
        this.pnlFuncionario = pnlFuncionario;
        this.controle = controle;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSul = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        btnSalvar.setText("Salvar");
        pnlSul.add(btnSalvar);

        btnCancelar.setText("Cancelar");
        pnlSul.add(btnCancelar);

        add(pnlSul, java.awt.BorderLayout.PAGE_END);

        pnlCentro.setLayout(new java.awt.GridBagLayout());
        add(pnlCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlSul;
    // End of variables declaration//GEN-END:variables
}
