
package br.edu.ifsul.cc.lpoo.cv.gui.funcionario;

import br.edu.ifsul.cc.lpoo.cv.Controle;
import br.edu.ifsul.cc.lpoo.cv.model.Funcionario;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;

/**
 *
 * @author bruno
 */
public class JPanelFuncionarioListagem extends javax.swing.JPanel {

    private JPanelFuncionario pnlFuncionario;
    private Controle controle;
    
    private SimpleDateFormat format;
    
    
    public JPanelFuncionarioListagem(JPanelFuncionario pnlFuncionario, Controle controle) {
        this.pnlFuncionario = pnlFuncionario;
        this.controle = controle;
        initComponents();
    }
    
    public void populaTable() {
        
        DefaultTableModel model =  (DefaultTableModel) tblListagem.getModel(); // Recuperação do modelo da tabela.

        model.setRowCount(0); // Elimina as linhas existentes (reset na tabela).

        try {

            List<Funcionario> listFuncionarios = controle.getConexaoJDBC().listFuncionarios();
            for(Funcionario f : listFuncionarios){
                                
                model.addRow(new Object[]{f, format.format(f.getData_cadastro().getTime()), f.getCep()});
            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Erro ao listar funcionários: " + ex.getLocalizedMessage(), "Funcionários", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNorte = new javax.swing.JPanel();
        lblFiltro = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        pnlSul = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();
        scpRolagem = new javax.swing.JScrollPane();
        tblListagem = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        lblFiltro.setText("Filtrar por CPF:");
        pnlNorte.add(lblFiltro);

        txtFiltro.setColumns(20);
        pnlNorte.add(txtFiltro);

        btnFiltrar.setText("Filtrar");
        pnlNorte.add(btnFiltrar);

        add(pnlNorte, java.awt.BorderLayout.PAGE_START);

        btnNovo.setText("Novo");
        pnlSul.add(btnNovo);

        btnEditar.setText("Editar");
        pnlSul.add(btnEditar);

        btnRemover.setText("Remover");
        pnlSul.add(btnRemover);

        add(pnlSul, java.awt.BorderLayout.PAGE_END);

        pnlCentro.setLayout(new java.awt.BorderLayout());

        tblListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Data Cadastro", "CEP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpRolagem.setViewportView(tblListagem);

        pnlCentro.add(scpRolagem, java.awt.BorderLayout.CENTER);

        add(pnlCentro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JPanel pnlSul;
    private javax.swing.JScrollPane scpRolagem;
    private javax.swing.JTable tblListagem;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
    
    
}
